---
title: "Gene Expression Heatmaps for *L. zosterae*"
author: "Grace Crandall (Based on Yaamini V.'s markdown file)"
date: "7/16/2019"
output: github_document
---

In this R Markdown document, I will create heatmaps for *L. zosterae* gene expression.

# Set up R Markdown document

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Install packages

```{r}
#install.packages("pheatmap") #Uncomment if you need to install this package
require(pheatmap)
```

```{r}
#install.packages("dplyr") #Uncomment if you need to install this package
require(dplyr)
```

# Obtain session information

```{r}
sessionInfo()
```

# *L. zosterae* heatmaps
I deleted all those to do with *Z. marina*

## Create color scheme

```{r}
heatmapBrown <- RColorBrewer::brewer.pal(9, "YlOrBr") #Save yellow-orange-brown color palette from RColorBrewer
```

## Subset genes of interest from large DE gene list

```{r}
nZostera.GE<-read.delim("EXP.CON.nZostera.logCPM.txt", header=TRUE) #Import logCPM file
head(nZostera.GE) #Confirm import
```

```{r}
rownames(nZostera.GE) <- nZostera.GE$GeneID #Set gene ID as row names
nZostera.GE.heatmap <- nZostera.GE[,-1] #Remove redundant column
head(nZostera.GE.heatmap) #Confirm changes
```

Subset the genes from the non Zostera genes that are of interest
```{r}
require(dplyr)
include_list <- c("TRINITY_DN173970_c0_g1", "TRINITY_DN274805_c0_g2", "TRINITY_DN295224_c1_g1","TRINITY_DN296759_c4_g1")
nZostera.GE.heatmap.sub <- nZostera.GE.heatmap[include_list, ]
nZostera.GE.heatmap.sub
```

```{r}
#pdf("../../../../../Desktop/EIMD-2019/EWD-project/2019-07-16-nonZostera-DE-genes-of-interest.pdf", width = 11, height = 8.5)
pheatmap(nZostera.GE.heatmap.sub, cluster_row = TRUE, cluster_cols = FALSE, clustering_distance_rows = "euclidean", clustering_method = "average", show_rownames = TRUE, show_colnames = TRUE, treeheight_col = 80, legend = TRUE, color = heatmapBrown, fontsize_col = 20, fontsize_row = 12)
#dev.off()
#Create heatmap. Cluster rows, but not columns, Use euclidean distances and average method for clustering. Do not show rownames but show column names. Adjust tree height, add a legend, and specify colors and font sizes.

#Can change "show_rownmames = TRUE" to "show_rownames = FALSE" if you don't want the labels for the rows
```

